'use client';

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

type Option = { text: string; isCorrect: boolean };
type Question = { id: string; title?: string | null; text: string; category?: string | null; internalNotes?: string | null; type: string; isActive: boolean; mediaUrl?: string | null; mediaContentType?: string | null; options: Array<{ id: string; text: string; isCorrect: boolean }> };
type Quiz = { id: string; title: string; description?: string | null; mode: string; isActive: boolean; questions: Array<{ questionId: string; position: number; question: { id: string; text: string } }> };
const blankOptions = (): Option[] => [{ text: "", isCorrect: true }, { text: "", isCorrect: false }, { text: "", isCorrect: false }, { text: "", isCorrect: false }];

export default function QuizShowSettingsPage() {
  const { toast } = useToast();
  const [questions, setQuestions] = useState<Question[]>([]);
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [text, setText] = useState("");
  const [questionTitle, setQuestionTitle] = useState("");
  const [category, setCategory] = useState("");
  const [internalNotes, setInternalNotes] = useState("");
  const [type, setType] = useState("singleChoice");
  const [options, setOptions] = useState<Option[]>(blankOptions());
  const [media, setMedia] = useState<File | null>(null);
  const [mediaPreviewUrl, setMediaPreviewUrl] = useState<string | null>(null);
  const [mediaContentType, setMediaContentType] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [quizTitle, setQuizTitle] = useState("");
  const [quizDescription, setQuizDescription] = useState("");
  const [quizMode, setQuizMode] = useState("saved");
  const [quizQuestionIds, setQuizQuestionIds] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);

  const load = async () => { const [questionResponse, quizResponse] = await Promise.all([fetch("/api/settings/quiz-show/questions"), fetch("/api/settings/quiz-show/quizzes")]); const questionData = await questionResponse.json(); const quizData = await quizResponse.json(); setQuestions(questionData.questions || []); setQuizzes(quizData.quizzes || []); };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (type === "trueFalse") setOptions([{ text: "True", isCorrect: true }, { text: "False", isCorrect: false }]); else setOptions((current) => current.length === 2 && current[0].text === "True" && current[1].text === "False" ? blankOptions() : current); }, [type]);

  const correctCount = useMemo(() => options.filter((option) => option.isCorrect).length, [options]);
  const updateOption = (index: number, patch: Partial<Option>) => setOptions((current) => current.map((option, optionIndex) => optionIndex === index ? { ...option, ...patch } : option));
  const toggleCorrect = (index: number) => setOptions((current) => current.map((option, optionIndex) => type === "multipleChoice" ? optionIndex === index ? { ...option, isCorrect: !option.isCorrect } : option : { ...option, isCorrect: optionIndex === index }));
  const uploadMedia = async () => { if (!media) return null; const formData = new FormData(); formData.append("media", media); const response = await fetch("/api/settings/quiz-show/media", { method: "POST", body: formData }); if (!response.ok) throw new Error((await response.json()).error || "Media upload failed."); return response.json(); };
  const saveQuestion = async () => {
    setBusy(true);
    try { const uploaded = await uploadMedia(); const response = await fetch(editingId ? `/api/settings/quiz-show/questions/${editingId}` : "/api/settings/quiz-show/questions", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: questionTitle || null, text, category: category || null, internalNotes: internalNotes || null, type, options: options.map((option, position) => ({ ...option, position })), ...(uploaded || {}) }) }); if (!response.ok) throw new Error((await response.json()).error || "Question could not be saved."); setText(""); setQuestionTitle(""); setCategory(""); setInternalNotes(""); setOptions(blankOptions()); setMedia(null); setMediaPreviewUrl(null); setMediaContentType(null); setEditingId(null); await load(); toast({ title: editingId ? "Question updated" : "Question saved" }); } catch (error) { toast({ variant: "destructive", title: "Could not save question", description: error instanceof Error ? error.message : "Please try again." }); } finally { setBusy(false); }
  };
  const saveQuiz = async () => { setBusy(true); try { const response = await fetch("/api/settings/quiz-show/quizzes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: quizTitle, description: quizDescription || null, mode: quizMode, questionIds: quizQuestionIds, questionCount: quizMode === "random" ? Math.max(1, quizQuestionIds.length || 10) : null }) }); if (!response.ok) throw new Error((await response.json()).error || "Quiz could not be saved."); setQuizTitle(""); setQuizDescription(""); setQuizQuestionIds([]); await load(); toast({ title: "Quiz saved" }); } catch (error) { toast({ variant: "destructive", title: "Could not save quiz", description: error instanceof Error ? error.message : "Please try again." }); } finally { setBusy(false); } };
  const deleteQuestion = async (id: string) => { if (!confirm("Delete this question? It cannot be deleted if it is used by a quiz or room.")) return; const response = await fetch(`/api/settings/quiz-show/questions/${id}`, { method: "DELETE" }); if (!response.ok) toast({ variant: "destructive", title: "Question could not be deleted" }); await load(); };
  const toggleQuestion = async (question: Question) => { const response = await fetch(`/api/settings/quiz-show/questions/${question.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: question.title || null, text: question.text, category: question.category || null, internalNotes: question.internalNotes || null, type: question.type, isActive: !question.isActive, options: question.options.map((option, position) => ({ text: option.text, position, isCorrect: option.isCorrect })), mediaUrl: question.mediaUrl || null, mediaContentType: question.mediaContentType || null }) }); if (!response.ok) toast({ variant: "destructive", title: "Question could not be updated" }); await load(); };
  const editQuestion = (question: Question) => { setEditingId(question.id); setQuestionTitle(question.title || ""); setText(question.text); setCategory(question.category || ""); setInternalNotes(question.internalNotes || ""); setType(question.type); setOptions(question.options.map((option) => ({ text: option.text, isCorrect: option.isCorrect }))); setMedia(null); setMediaPreviewUrl(question.mediaUrl || null); setMediaContentType(question.mediaContentType || null); };
  const chooseMedia = (file: File | null) => { setMedia(file); setMediaContentType(file?.type || null); setMediaPreviewUrl(file ? URL.createObjectURL(file) : null); };
  const deleteQuiz = async (id: string) => { if (!confirm("Delete this quiz? Existing rooms retain their question snapshot.")) return; const response = await fetch(`/api/settings/quiz-show/quizzes/${id}`, { method: "DELETE" }); if (!response.ok) toast({ variant: "destructive", title: "Quiz could not be deleted" }); await load(); };
  return <div className="mx-auto max-w-6xl space-y-6">
    <div><h1 className="text-3xl font-bold">Quiz Show</h1><p className="text-muted-foreground">Create shared questions and reusable quizzes for live team games.</p></div>
    <div className="grid gap-6 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>{editingId ? "Edit question" : "Add question"}</CardTitle><CardDescription>Use the internal title and category to distinguish similar questions in the bank. Players only see the question text.</CardDescription></CardHeader><CardContent className="space-y-4">{mediaPreviewUrl && (mediaContentType?.startsWith("video/") ? <video controls className="max-h-64 w-full rounded-lg" src={mediaPreviewUrl} /> : <img className="max-h-64 w-full rounded-lg object-contain" src={mediaPreviewUrl} alt="Question media preview" />)}<Input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/ogg" onChange={(event) => chooseMedia(event.target.files?.[0] || null)} /><Input value={questionTitle} onChange={(event) => setQuestionTitle(event.target.value)} maxLength={160} placeholder="Internal title, e.g. Electricity meter — Example 1" /><Input value={category} onChange={(event) => setCategory(event.target.value)} maxLength={80} placeholder="Category, e.g. Meter readings" /><Textarea value={internalNotes} onChange={(event) => setInternalNotes(event.target.value)} maxLength={1_000} placeholder="Internal notes (optional)" /><Textarea value={text} onChange={(event) => setText(event.target.value)} maxLength={1_000} placeholder="What is this meter reading?" /><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={type} onChange={(event) => setType(event.target.value)}><option value="singleChoice">Single choice</option><option value="trueFalse">True / false</option><option value="multipleChoice">Multiple correct</option></select><div className="space-y-2">{options.map((option, index) => <div className="flex items-center gap-2" key={index}><button type="button" className={`h-8 w-8 rounded-full border text-sm ${option.isCorrect ? "border-primary bg-primary text-primary-foreground" : ""}`} onClick={() => toggleCorrect(index)} aria-label={`Mark option ${index + 1} correct`}>{String.fromCharCode(65 + index)}</button><Input value={option.text} onChange={(event) => updateOption(index, { text: event.target.value })} placeholder={`Answer ${index + 1}`} maxLength={240} /></div>)}</div><p className="text-xs text-muted-foreground">{correctCount} correct option{correctCount === 1 ? "" : "s"} selected.</p><div className="flex gap-2"><Button onClick={() => void saveQuestion()} disabled={busy || !text.trim() || options.some((option) => !option.text.trim())}>{editingId ? "Update question" : "Save question"}</Button>{editingId && <Button variant="outline" onClick={() => { setEditingId(null); setText(""); setQuestionTitle(""); setCategory(""); setInternalNotes(""); setOptions(blankOptions()); setMedia(null); setMediaPreviewUrl(null); setMediaContentType(null); }}>Cancel</Button>}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Create quiz</CardTitle><CardDescription>Saved quizzes use the selected order. Random quizzes draw from the selected questions, or the active bank when none are selected.</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={quizTitle} onChange={(event) => setQuizTitle(event.target.value)} maxLength={120} placeholder="Friday knowledge quiz" /><Textarea value={quizDescription} onChange={(event) => setQuizDescription(event.target.value)} maxLength={500} placeholder="Optional description" /><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={quizMode} onChange={(event) => setQuizMode(event.target.value)}><option value="saved">Saved question list</option><option value="random">Random question draw</option></select><div className="max-h-52 space-y-2 overflow-y-auto rounded-md border p-3">{questions.filter((question) => question.isActive).map((question) => <label className="flex items-start gap-2 text-sm" key={question.id}><input type="checkbox" checked={quizQuestionIds.includes(question.id)} onChange={(event) => setQuizQuestionIds((current) => event.target.checked ? [...current, question.id] : current.filter((id) => id !== question.id))} /><span><span className="block font-medium">{question.title || question.text}</span>{question.title && <span className="block text-xs text-muted-foreground">{question.text}{question.category ? ` · ${question.category}` : ""}</span>}</span></label>)}{questions.length === 0 && <p className="text-sm text-muted-foreground">Create a question first.</p>}</div><Button onClick={() => void saveQuiz()} disabled={busy || !quizTitle.trim() || (quizMode === "saved" && quizQuestionIds.length === 0)}>Save quiz</Button></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Question bank</CardTitle></CardHeader><CardContent className="space-y-2">{questions.map((question) => <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3" key={question.id}><div className="min-w-0 flex-1"><p className="font-medium">{question.title || question.text}</p><p className="text-sm text-muted-foreground">{question.text}</p><p className="text-xs text-muted-foreground">{question.category || "Uncategorised"} · {question.type} · {question.isActive ? "Active" : "Inactive"}{question.mediaUrl ? " · Media attached" : ""}</p></div><Button size="sm" variant="outline" onClick={() => editQuestion(question)}>Edit</Button><Button size="sm" variant="outline" onClick={() => void toggleQuestion(question)}>{question.isActive ? "Deactivate" : "Activate"}</Button><Button size="sm" variant="destructive" onClick={() => void deleteQuestion(question.id)}>Delete</Button></div>)}{questions.length === 0 && <p className="py-6 text-center text-muted-foreground">No questions yet.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Saved quizzes</CardTitle></CardHeader><CardContent className="space-y-2">{quizzes.map((quiz) => <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3" key={quiz.id}><div className="min-w-0 flex-1"><p className="font-semibold">{quiz.title}</p><p className="text-sm text-muted-foreground">{quiz.mode === "random" ? "Random draw" : `${quiz.questions.length} saved questions`} · {quiz.isActive ? "Active" : "Inactive"}</p></div><Button size="sm" variant="destructive" onClick={() => void deleteQuiz(quiz.id)}>Delete</Button></div>)}{quizzes.length === 0 && <p className="py-6 text-center text-muted-foreground">No quizzes yet.</p>}</CardContent></Card>
  </div>;
}
