"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Pencil, X } from "lucide-react";
import { EmojiPickerField } from "@/components/ui/emoji-picker-field";

type User = { id: string; name: string };
type Absence = { id: string; userId: string; userName: string; startsOn: string; endsOn?: string | null; reason?: string | null; emoji?: string | null };

export default function AbsencesPage() {
  const { toast } = useToast(); const [users, setUsers] = useState<User[]>([]); const [absences, setAbsences] = useState<Absence[]>([]); const [userId, setUserId] = useState(""); const [startsOn, setStartsOn] = useState(""); const [endsOn, setEndsOn] = useState(""); const [endUnknown, setEndUnknown] = useState(false); const [reason, setReason] = useState(""); const [emoji, setEmoji] = useState(""); const [editingId, setEditingId] = useState<string | null>(null);
  const load = async () => { const [usersResult, absenceResult] = await Promise.all([fetch('/api/users'), fetch('/api/absences')]); if (usersResult.ok) { const data = await usersResult.json(); setUsers(data.users || []); } if (absenceResult.ok) { const data = await absenceResult.json(); setAbsences(data.absences || []); } };
  useEffect(() => { load().catch(() => undefined); }, []);
  const resetForm = () => { setUserId(''); setStartsOn(''); setEndsOn(''); setEndUnknown(false); setReason(''); setEmoji(''); setEditingId(null); };
  const startEdit = (absence: Absence) => { setEditingId(absence.id); setUserId(absence.userId); setStartsOn(absence.startsOn.slice(0, 10)); setEndsOn(absence.endsOn?.slice(0, 10) ?? ''); setEndUnknown(!absence.endsOn); setReason(absence.reason ?? ''); setEmoji(absence.emoji ?? ''); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const payload = { startsOn: new Date(`${startsOn}T00:00:00Z`).toISOString(), endsOn: endUnknown ? null : new Date(`${endsOn}T23:59:59Z`).toISOString(), reason: reason || null, emoji: emoji || null }; const response = await fetch(editingId ? `/api/absences/${editingId}` : '/api/absences', { method: editingId ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editingId ? payload : { ...payload, userId }) }); const data = await response.json(); if (!response.ok) { toast({ variant: 'destructive', title: 'Absence not saved', description: data.error }); return; } resetForm(); await load(); toast({ title: editingId ? 'Absence updated' : 'Absence recorded' }); };
  return <div className="mx-auto max-w-4xl space-y-6"><div><h1 className="text-3xl font-bold">Absences</h1><p className="text-muted-foreground">Record leave without changing competition enrolment or earned scores.</p></div><Card><CardHeader><CardTitle>{editingId ? 'Edit absence' : 'Record absence'}</CardTitle></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-2" onSubmit={submit}>{editingId ? <Input value={users.find(user => user.id === userId)?.name ?? 'Selected user'} disabled /> : <Select value={userId} onValueChange={setUserId}><SelectTrigger><SelectValue placeholder="Select user" /></SelectTrigger><SelectContent>{users.map(user => <SelectItem key={user.id} value={user.id}>{user.name}</SelectItem>)}</SelectContent></Select>}<div className="grid grid-cols-2 gap-3"><Input type="date" value={startsOn} onChange={e=>setStartsOn(e.target.value)} required/><Input type="date" value={endsOn} onChange={e=>setEndsOn(e.target.value)} required disabled={endUnknown}/></div><EmojiPickerField value={emoji} onChange={setEmoji} placeholder="Absence emoji"/><label className="flex items-center gap-2 text-sm"><Checkbox checked={endUnknown} onCheckedChange={(checked) => setEndUnknown(checked === true)}/>End date unknown</label><Textarea className="md:col-span-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason (optional)"/><div className="flex gap-2 md:col-span-2"><Button disabled={!userId||!startsOn||(!endUnknown&&!endsOn)}>{editingId ? 'Update absence' : 'Save absence'}</Button>{editingId && <Button type="button" variant="outline" onClick={resetForm}><X className="mr-2 h-4 w-4"/>Cancel</Button>}</div></form></CardContent></Card><Card><CardHeader><CardTitle>Recorded absences</CardTitle></CardHeader><CardContent className="space-y-2">{absences.length===0?<p className="text-sm text-muted-foreground">No absences recorded.</p>:absences.map(absence=><div key={absence.id} className="flex items-start justify-between gap-3 rounded border p-3"><div><b>{absence.emoji && `${absence.emoji} `}{absence.userName}</b><span className="ml-2 text-sm text-muted-foreground">{new Date(absence.startsOn).toLocaleDateString()} – {absence.endsOn ? new Date(absence.endsOn).toLocaleDateString() : 'Unknown'}</span>{absence.reason&&<p className="mt-1 text-sm">{absence.reason}</p>}</div><Button type="button" variant="ghost" size="sm" onClick={() => startEdit(absence)}><Pencil className="mr-1 h-4 w-4"/>Edit</Button></div>)}</CardContent></Card></div>;
}
