'use client';

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Check, Clock, LogOut, Play, Trophy, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";

type Quiz = { id: string; title: string; mode: string; questions?: Array<{ questionId: string }> };
type State = { room: { code: string; phase: "lobby" | "answering" | "reveal" | "complete"; currentQuestion: number; totalQuestions: number; questionStartedAt?: string | null; answerDeadlineAt?: string | null; quiz: { title: string } }; viewer: { isHost: boolean; hasAnswered: boolean }; participants: Array<{ id: string; name: string; score: number; isHost: boolean }>; question: { id: string; position: number; text: string; type: string; mediaUrl?: string | null; mediaContentType?: string | null; options: Array<{ id: string; text: string; position: number; isCorrect?: boolean }> } | null; answer: { selectedOptionIds: string[]; isCorrect?: boolean; points?: number } | null; results?: { responseCount: number; distribution: Array<{ optionId: string; count: number }>; answers?: Array<{ participantId: string; selectedOptionIds: string[]; isCorrect: boolean; points: number }> } | null; leaderboard: Array<{ name: string; score: number }> };

function readState(data: any): State { return data as State; }

export default function QuizShowPage() {
  const { toast } = useToast();
  const [room, setRoom] = useState<State | null>(null);
  const [joinCode, setJoinCode] = useState("");
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [canManage, setCanManage] = useState(false);
  const [quizId, setQuizId] = useState("");
  const [shuffle, setShuffle] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [secondsLeft, setSecondsLeft] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);

  const request = async (url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Quiz Show request failed."); return body; };
  const loadRoom = useCallback(async (code: string) => { const data = await request(`/api/mini-games/quiz-show/rooms/${encodeURIComponent(code)}`); setRoom(readState(data)); sessionStorage.setItem("quiz-show-room-code", code.toUpperCase()); }, []);
  useEffect(() => { const saved = sessionStorage.getItem("quiz-show-room-code"); if (saved) void loadRoom(saved).catch(() => sessionStorage.removeItem("quiz-show-room-code")); void fetch("/api/settings/quiz-show/quizzes").then(async (response) => { if (!response.ok) return null; setCanManage(true); return response.json(); }).then((data) => { if (data?.quizzes) { setQuizzes(data.quizzes); setQuizId(data.quizzes[0]?.id || ""); } }).catch(() => undefined); }, [loadRoom]);
  useEffect(() => { if (!room?.room.code) return; const events = new EventSource(`/api/mini-games/quiz-show/rooms/${encodeURIComponent(room.room.code)}/events`); const refresh = () => void loadRoom(room.room.code).catch(() => undefined); events.addEventListener("room-state", refresh); events.addEventListener("question-started", refresh); events.addEventListener("answer", refresh); events.addEventListener("reveal", refresh); events.addEventListener("complete", refresh); events.onerror = () => events.close(); return () => events.close(); }, [loadRoom, room?.room.code]);
  useEffect(() => { if (!room?.room.answerDeadlineAt || room.room.phase !== "answering") { setSecondsLeft(null); return; } const tick = () => setSecondsLeft(Math.max(0, Math.ceil((new Date(room.room.answerDeadlineAt as string).getTime() - Date.now()) / 1000))); tick(); const timer = window.setInterval(tick, 250); return () => window.clearInterval(timer); }, [room?.room.answerDeadlineAt, room?.room.phase]);
  useEffect(() => { setSelected(room?.answer?.selectedOptionIds || []); }, [room?.question?.id, room?.answer?.selectedOptionIds]);

  const act = async (action: string, payload: Record<string, unknown> = {}) => { if (!room) return; setBusy(true); try { const data = await request(`/api/mini-games/quiz-show/rooms/${encodeURIComponent(room.room.code)}`, { method: "POST", body: JSON.stringify({ action, ...payload }) }); setRoom(readState(data)); } catch (error) { toast({ variant: "destructive", title: "Quiz Show", description: error instanceof Error ? error.message : "Please try again." }); } finally { setBusy(false); } };
  const createRoom = async () => { if (!quizId) return; setBusy(true); try { const data = await request("/api/mini-games/quiz-show/rooms", { method: "POST", body: JSON.stringify({ quizId, shuffleQuestions: shuffle }) }); setRoom(readState(data.room)); sessionStorage.setItem("quiz-show-room-code", data.room.room.code); } catch (error) { toast({ variant: "destructive", title: "Could not create room", description: error instanceof Error ? error.message : "Please try again." }); } finally { setBusy(false); } };
  const joinRoom = async () => { setBusy(true); try { const data = await request("/api/mini-games/quiz-show/rooms/join", { method: "POST", body: JSON.stringify({ code: joinCode.trim().toUpperCase() }) }); setRoom(readState(data.room)); sessionStorage.setItem("quiz-show-room-code", joinCode.trim().toUpperCase()); } catch (error) { toast({ variant: "destructive", title: "Could not join room", description: error instanceof Error ? error.message : "Check the room code." }); } finally { setBusy(false); } };
  const exit = () => { sessionStorage.removeItem("quiz-show-room-code"); setRoom(null); setJoinCode(""); };
  const toggleOption = (id: string) => { if (room?.viewer.hasAnswered) return; setSelected((current) => room?.question?.type === "multipleChoice" ? current.includes(id) ? current.filter((item) => item !== id) : [...current, id] : [id]); };
  const canAnswer = Boolean(room?.room.phase === "answering" && room.question && !room.viewer.hasAnswered && secondsLeft !== 0);
  const answerLabel = useMemo(() => room?.question?.type === "multipleChoice" ? "Submit answers" : "Submit answer", [room?.question?.type]);

  if (!room) return <div className="mx-auto max-w-5xl space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Quiz Show</h1><p className="text-muted-foreground">Answer live questions, climb the leaderboard, and see who knows their stuff.</p></div>{canManage && <Button asChild variant="outline"><Link href="/settings/quiz-show">Manage questions and quizzes</Link></Button>}</div><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Host a game</CardTitle><CardDescription>Select a reusable quiz and share the room code.</CardDescription></CardHeader><CardContent className="space-y-4"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={quizId} onChange={(event) => setQuizId(event.target.value)}><option value="">Select a quiz</option>{quizzes.map((quiz) => <option value={quiz.id} key={quiz.id}>{quiz.title}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={shuffle} onChange={(event) => setShuffle(event.target.checked)} />Shuffle questions</label><Button onClick={() => void createRoom()} disabled={busy || !quizId}><Play className="mr-2 h-4 w-4" />Create room</Button>{quizzes.length === 0 && <p className="text-sm text-muted-foreground">Only Quiz Show managers can create rooms and quizzes.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Join a game</CardTitle><CardDescription>Enter the room code from your host.</CardDescription></CardHeader><CardContent className="flex gap-2"><Input value={joinCode} onChange={(event) => setJoinCode(event.target.value.toUpperCase())} maxLength={8} placeholder="ROOM CODE" onKeyDown={(event) => event.key === "Enter" && void joinRoom()} /><Button onClick={() => void joinRoom()} disabled={busy || !joinCode.trim()}>Join</Button></CardContent></Card></div></div>;

  const isVideo = room.question?.mediaContentType?.startsWith("video/");
  return <div className="mx-auto max-w-5xl space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Quiz Show</h1><p className="text-muted-foreground">{room.room.quiz.title} · Room <span className="font-mono font-bold tracking-widest text-foreground">{room.room.code}</span></p></div><div className="rounded-lg border bg-muted/30 px-4 py-2 text-center"><p className="text-xs uppercase tracking-wider text-muted-foreground">{room.room.phase === "complete" ? "Complete" : `Question ${Math.max(0, room.room.currentQuestion + 1)} of ${room.room.totalQuestions}`}</p><p className="font-semibold capitalize">{room.room.phase}</p></div></div>
    {room.room.phase === "lobby" && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5" />Waiting room</CardTitle><CardDescription>Share the code, then start the first question when ready.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex flex-wrap gap-2">{room.participants.map((participant) => <span className="rounded-full border px-3 py-1 text-sm" key={participant.id}>{participant.name}{participant.isHost ? " (host)" : ""}</span>)}</div>{room.viewer.isHost ? <Button onClick={() => void act("start")} disabled={busy}>Start first question</Button> : <p className="text-sm text-muted-foreground">Waiting for the host…</p>}</CardContent></Card>}
    {room.question && room.room.phase !== "complete" && <Card><CardHeader><CardDescription>{room.room.phase === "reveal" ? "Answer revealed" : "Question"}</CardDescription><CardTitle className="text-2xl">{room.question.text}</CardTitle></CardHeader><CardContent className="space-y-5">{room.question.mediaUrl && (isVideo ? <video controls className="max-h-80 w-full rounded-lg" src={room.question.mediaUrl} /> : <img className="max-h-80 w-full rounded-lg object-contain" src={room.question.mediaUrl} alt="Question media" />)}{room.room.phase === "answering" && <div className="flex items-center gap-2 text-sm font-semibold"><Clock className="h-4 w-4" />{secondsLeft === null ? "Waiting for timer…" : `${secondsLeft}s remaining`}</div>}<div className="grid gap-3 sm:grid-cols-2">{room.question.options.map((option, index) => { const chosen = selected.includes(option.id); const correct = room.room.phase === "reveal" && option.isCorrect; return <button type="button" key={option.id} disabled={!canAnswer} onClick={() => toggleOption(option.id)} className={`rounded-lg border p-4 text-left transition ${chosen ? "border-primary bg-primary/10" : ""} ${correct ? "border-green-500 bg-green-500/10" : ""}`}><span className="mr-2 font-bold">{String.fromCharCode(65 + index)}.</span>{option.text}{room.room.phase === "reveal" && (correct ? <Check className="float-right h-5 w-5 text-green-600" /> : chosen ? <X className="float-right h-5 w-5 text-red-600" /> : null)}</button>; })}</div>{room.room.phase === "answering" && <Button onClick={() => void act("answer", { selectedOptionIds: selected })} disabled={busy || !canAnswer || selected.length === 0}>{answerLabel}</Button>}{room.viewer.hasAnswered && room.room.phase === "answering" && <p className="text-sm text-muted-foreground">Answer recorded. Waiting for the reveal…</p>}{room.viewer.isHost && room.room.phase === "answering" && <Button variant="outline" onClick={() => void act("reveal")} disabled={busy}>Close answers and reveal</Button>}{room.room.phase === "reveal" && <div className="rounded-lg border bg-muted/30 p-4"><p className="font-semibold">{room.results?.responseCount || 0} answer{room.results?.responseCount === 1 ? "" : "s"} received</p><p className="text-sm text-muted-foreground">Correct answers: {room.question.options.filter((option) => option.isCorrect).map((option) => option.text).join(", ")}</p>{room.answer && <p className="mt-2 text-sm">Your result: {room.answer.isCorrect ? `${room.answer.points} points` : "Incorrect"}</p>}</div>}{room.viewer.isHost && room.room.phase === "reveal" && <Button onClick={() => void act("start")} disabled={busy}>{room.room.currentQuestion + 1 >= room.room.totalQuestions ? "Show final leaderboard" : "Start next question"}</Button>}</CardContent></Card>}
    {room.room.phase === "complete" && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Trophy className="h-5 w-5 text-amber-500" />Final leaderboard</CardTitle></CardHeader><CardContent className="space-y-3">{room.leaderboard.map((player, index) => <div className="flex items-center gap-3 rounded-lg border px-4 py-3" key={`${player.name}-${index}`}><span className="w-8 text-xl font-bold">{index + 1}</span><span className="flex-1 font-semibold">{player.name}</span><span>{player.score} points</span></div>)}<Button variant="outline" onClick={exit}><LogOut className="mr-2 h-4 w-4" />Exit game</Button></CardContent></Card>}
  </div>;
}
