"use client";
import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
type Item = { id:string; title:string; message:string; isActive:boolean; createdAt:string };
export default function MotdPage() { const { toast }=useToast(); const [items,setItems]=useState<Item[]>([]); const [title,setTitle]=useState(""); const [message,setMessage]=useState(""); const [editing,setEditing]=useState<string|null>(null); const load=()=>fetch('/api/announcements?all=true').then(r=>r.json()).then(d=>setItems(d.announcements||[])); useEffect(()=>{load();},[]); const save=async()=>{const r=await fetch(editing?`/api/announcements/${editing}`:'/api/announcements',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,message})}); if(!r.ok){toast({variant:'destructive',title:'Could not save message'});return;} setTitle('');setMessage('');setEditing(null);load();}; return <div className="mx-auto max-w-3xl space-y-6"><div><h1 className="text-3xl font-bold">Message of the Day</h1><p className="text-muted-foreground">Publish and manage signed-in announcements.</p></div><Card><CardContent className="space-y-3 pt-6"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title"/><Textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message"/><Button disabled={!title.trim()||!message.trim()} onClick={save}>{editing?'Save changes':'Publish message'}</Button>{editing&&<Button variant="outline" className="ml-2" onClick={()=>{setEditing(null);setTitle('');setMessage('');}}>Cancel</Button>}</CardContent></Card><Card><CardHeader><CardTitle>Current and recent</CardTitle></CardHeader><CardContent className="space-y-3">{items.map(i=><div className="rounded border p-3" key={i.id}><div className="flex justify-between gap-3"><b>{i.title}</b><span className="text-xs">{i.isActive?'Active':'Replaced'}</span></div><p className="mt-1 whitespace-pre-wrap text-sm">{i.message}</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setEditing(i.id);setTitle(i.title);setMessage(i.message)}}>Edit</Button><Button size="sm" variant="destructive" onClick={async()=>{if(confirm('Delete this message?')){await fetch(`/api/announcements/${i.id}`,{method:'DELETE'});load();}}}>Delete</Button></div></div>)}</CardContent></Card></div>; }
